# basic options
title: Salesforce Lightning blog
author: Jonathan Dawson
email: jonathan@akavy.com
description: A blog all about Salesforce Lightning
twitter_username: akavy
github_username:  akavy

# Build settings
markdown: kramdown
theme: minima
